### ISSUE TITLE
这个项目还在维护吗？（Is this repo still maintained?）

### ISSUE THREAD

**Issue by AkatQuas** [nscript-cn/docs-cn#17]
NativeScript 文档翻译的工作还在继续吗？

Are you still working on translating the documents of NativeScripts?

**Comment by jadertao** [comment]
yes... but moving slowly.

**Comment by asnowwolf** [comment]
抱歉，以前卡在文档编译问题上没解决，加上在忙别的，就放下了。下周我再试试新版文档能不能编译。

**Comment by asnowwolf** [comment]
会等 ngChina 结束后继续。
